version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ames_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ames_housing
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: ames_api
    ports:
      - "10000:10000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: